version: "3.9"

networks:
  samwaktou-network:

services:
  tontou-fatwa-backend-api:
    container_name: backend-api
    image: tontou-fatwa/backend-api:1.0.0.beta
    restart: always
    ports:
      - 8080:8080
    # depends_on:
      # - mongodb
      # - minio
    networks:
      - samwaktou-network

  tontou-fatwa-frontend:
    container_name: frontend
    image: tontou-fatwa/frontend-react:1.0.0.beta
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - tontou-fatwa-backend-api
    networks:
      - samwaktou-network