/**
 * @file activity-log.interface.ts
 * @description Database-agnostic interface for the ActivityLog entity.
 *
 * Activity logs provide an immutable audit trail of every significant action
 * performed on tasks, audio drafts, and themes. They are append-only —
 * once created, a log entry is never updated or deleted.
 *
 * Each entry records **who** did **what** to **which** entity, with an
 * optional free-form `details` bag for action-specific context.
 */

/* ── Allowed entity types ────────────────────────────────────────────── */

/**
 * The type of domain entity that the activity log entry relates to.
 * Used for filtering and grouping when displaying an entity's history.
 */
export type ActivityEntityType = 'task' | 'audio_draft' | 'theme';

/* ── ActivityLog read-model ──────────────────────────────────────────── */

/** Read-model representation of an ActivityLog entry. */
export interface IActivityLog {
  /** Unique identifier (mapped from the DB primary key). */
  id: string;
  /** The kind of entity this log entry relates to. */
  entityType: ActivityEntityType;
  /** ID of the related entity (task, audio-draft, or theme). */
  entityId: string;
  /** Human-readable action name (e.g. "TASK_CREATED", "DRAFT_APPROVED"). */
  action: string;
  /** Admin ID of the user who performed the action. */
  performedBy: string;
  /** Optional key-value bag with action-specific details (e.g. old/new status). */
  details: Record<string, unknown>;
  /** Record creation timestamp (Mongoose `timestamps` — createdAt only). */
  createdAt: Date;
}

/* ── Create type ─────────────────────────────────────────────────────── */

/**
 * Fields required when creating a new activity log entry.
 * `id` and `createdAt` are auto-generated by the database.
 */
export type IActivityLogCreate = Omit<IActivityLog, 'id' | 'createdAt'>;
