/**
 * @file admin.interface.ts
 * @description Database-agnostic interface for the Admin entity.
 *
 * These types are the **single source of truth** for the Admin shape used
 * across services, controllers, and routes. They intentionally contain no
 * Mongoose/DB-specific details so the domain layer stays portable.
 *
 * Phase 1 changes:
 * - `isSuperAdmin: boolean` replaced by `role: AdminRole` (four-tier RBAC).
 * - `date: Date` replaced by `createdAt` / `updatedAt` (Mongoose timestamps).
 * - Added `isActive: boolean` for soft-disable without deletion.
 */

import type { AdminRole } from '../../config/constants.js';

/** Read-model representation of an Admin (as returned by the repository). */
export interface IAdmin {
  /** Unique identifier (mapped from the DB's primary key, e.g. Mongo `_id`). */
  id: string;
  /** First name / surname, capitalised (e.g. "Thierno"). */
  surname: string;
  /** Last name, upper-cased (e.g. "DIALLO"). */
  name: string;
  /** Email address, lower-cased — used as the login identifier. */
  email: string;
  /** Bcrypt-hashed password — never exposed to the client. */
  password: string;
  /**
   * RBAC role that determines the admin's privilege level.
   * @see AdminRole  for the four-tier hierarchy.
   * @see ROLE_HIERARCHY  for the numeric ordering.
   */
  role: AdminRole;
  /** Whether the account is active.  Inactive admins cannot log in. */
  isActive: boolean;
  /** Record creation timestamp (managed by Mongoose `timestamps`). */
  createdAt: Date;
  /** Record last-update timestamp (managed by Mongoose `timestamps`). */
  updatedAt: Date;
}

/**
 * Fields required when creating a new admin.
 * `id`, `createdAt`, and `updatedAt` are auto-generated by the database.
 */
export type IAdminCreate = Omit<IAdmin, 'id' | 'createdAt' | 'updatedAt'>;

/**
 * Fields that may be updated on an existing admin (all optional).
 * `id`, `createdAt`, and `updatedAt` are immutable / auto-managed.
 */
export type IAdminUpdate = Partial<Omit<IAdmin, 'id' | 'createdAt' | 'updatedAt'>>;
